% Useful constants
DEG2RAD = pi/180;
KILO_RPM_TO_RAD_PER_SEC = 2000*pi/60;

% Potentiometers
global POTENTIOMETERS

POTENTIOMETER_01.DEGREES_PER_VOLT = 35.2;
POTENTIOMETER_01.RADIANS_PER_VOLT = DEG2RAD*POTENTIOMETER_01.DEGREES_PER_VOLT;
POTENTIOMETER_01.CONNECTION = 0;
POTENTIOMETERS{1} = POTENTIOMETER_01;

% Tachometers
global TACHOMETERS

TACHOMETER_01.VOLTS_PER_KILO_RPM = 1.5;
TACHOMETER_01.VOLTS_PER_RAD_PER_SEC = TACHOMETER_01.VOLTS_PER_KILO_RPM/KILO_RPM_TO_RAD_PER_SEC;
TACHOMETER_01.CONNECTION = 2;
TACHOMETERS{1} = TACHOMETER_01;

clear DEG2RAD;
