for i = 1:size(ENCODERS)
    hil_set_encoder_quadrature_mode( ...
        TERMINAL.TERMINAL_HANDLE, ENCODERS{i}.CONNECTION, ...
        ENCODERS{i}.ENCODER_QUADRATURE_MODE ...
    );
    hil_set_encoder_counts( ...
        TERMINAL.TERMINAL_HANDLE, ENCODERS{i}.CONNECTION, ...
        ENCODERS{i}.ENCODER_INITIAL_VALUE ...
    );
end

clear i;
