function angle = read_encoder_rad(encoder)
    load('constants');
    angle = ENCODERS{encoder}.ENCODER_TO_RADIANS*hil_read_encoder( ...
        TERMINAL.TERMINAL_HANDLE, ENCODERS{encoder}.CONNECTION ...
    );
end
